from enum import Enum


class VehicleRequestStatus(str, Enum):
    IN_PROGRESS = "IN_PROGRES"
    COMPLETED = "COMPLETED"
    WAITING = "WAITING"


class VehicleStatusEnum(str, Enum):
    AVAILABLE = "AVAILABLE"
    RENTED = "RENTED"
    UNAVAILABLE_IN_MAINTENANCE = "UNAVAILABLE_IN_MAINTENANCE"
    UNAVAILABLE_IN_SERVICE = "UNAVAILABLE_IN_SERVICE"
    UNAVAILABLE_DONOR = "UNAVAILABLE_DONOR"
    UNAVAILABLE_STOLEN = "UNAVAILABLE_STOLEN"
